#!/bin/bash

function usage {
    echo "usage: $0 <test_container_file>"
    exit 1
}

if [ $# -ne 1 ]; then usage; fi

CONTAINERS=$1

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ ! -f $CONTAINERS ]; then
    echo "No such file: $CONTAINERS"
    usage
fi

sed -e 's/\#.*//' -e '/^[ \t]*$/d' $CONTAINERS |
    while read NAME HOST DEV MAC; do
	sudo docker stop $NAME 2> /dev/null
	sudo docker rm $NAME 2> /dev/null
    done
